"""
strategy_engine.py
──────────────────
The interview strategy engine. Pure Python — zero LLM calls, zero I/O.
Decides WHAT to ask next, on WHICH topic, at WHAT depth, and WHY.

Architecture position:
    Session State → StrategyEngine.decide() → QuestionIntent → LLM (phrasing only)

The LLM receives a QuestionIntent and writes natural language for it.
The LLM never decides topic, type, difficulty, or concept node.

To plug in other components:
    - QuestionGenerator receives QuestionIntent and returns question text
    - EvaluationEngine calls update_after_evaluation() after each answer
    - RepetitionGuard calls get_asked_concept_nodes() for its Layer 3 check

To tune interview style:
    - Adjust PHASE_WEIGHTS for each phase
    - Adjust TURN_BUDGET_PER_LEVEL for session length
    - Adjust DEPTH_REQUIREMENT per candidate level
    - Adjust CONCEPT_TAXONOMY to add/remove concept nodes
"""

from __future__ import annotations
import time
from dataclasses import dataclass, field
from typing import Optional
from enum import Enum


# ══════════════════════════════════════════════════════════════════════════════
# ENUMERATIONS — type safety across all components
# ══════════════════════════════════════════════════════════════════════════════

class Phase(str, Enum):
    WARMUP  = "warmup"
    EARLY   = "early"    # turns 1–6:   breadth priority, foundational/basic only
    MID     = "mid"      # turns 7–14:  balanced, intermediate/advanced unlocked
    LATE    = "late"     # turns 15–18: exploitation, weakness confirmation
    CLOSING = "closing"  # turns 19–20: wrap up, no new topics

class QuestionType(str, Enum):
    DEFINITION      = "definition"
    SCENARIO        = "scenario"
    WHY_PROBE       = "why_probe"
    NUMERICAL       = "numerical"
    CONTRADICTION   = "contradiction"
    PERSONAL_ANCHOR = "personal_anchor"
    RECOVERY_PROBE  = "recovery_probe"
    PRACTICAL_EXAMPLE = "practical_example"
    WARMUP          = "warmup"
    GREETING        = "greeting"

class Difficulty(str, Enum):
    FOUNDATIONAL = "foundational"   # level index 0
    BASIC        = "basic"          # level index 1
    INTERMEDIATE = "intermediate"   # level index 2
    ADVANCED     = "advanced"       # level index 3
    EXPERT       = "expert"         # level index 4

class Confidence(str, Enum):
    UNTESTED          = "untested"
    INTRODUCED        = "introduced"   # 1 turn at any depth
    CONFIRMED         = "confirmed"    # 2+ turns, reached required depth
    EXHAUSTED         = "exhausted"    # fully covered, do not revisit

class WeakFlag(str, Enum):
    NONE              = "none"
    SUSPECTED         = "suspected"    # 1 weak signal — needs confirmation
    CONFIRMED_WEAK    = "confirmed_weak"
    CONFIRMED_STRONG  = "confirmed_strong"

class CandidateLevel(str, Enum):
    FRESH_GRADUATE    = "fresh_graduate"      # level index 0
    TRAINED_FRESHER   = "trained_fresher"     # level index 1
    EXPERIENCED_JUNIOR = "experienced_junior" # level index 2
    EXPERIENCED_SENIOR = "experienced_senior" # level index 3


# ══════════════════════════════════════════════════════════════════════════════
# CONCEPT TAXONOMY
# Domain-expert-defined. Static. Version-controlled. Never generated by LLM.
# To add a domain: add a new key to CONCEPT_TAXONOMY.
# To add a concept node: add to the appropriate topic list.
# Depth values map to Difficulty enum indices (0=foundational, 4=expert).
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class ConceptNode:
    node_id: str          # unique identifier, used as dict key
    topic: str            # parent topic name
    description: str      # what this node tests — given to LLM as constraint
    depth: int            # 0=foundational, 1=basic, 2=intermediate, 3=advanced, 4=expert
    keywords: list[str]   # for post-generation classifier sanity check
    prerequisite: Optional[str] = None  # concept_node_id that should be tested first


CONCEPT_TAXONOMY: dict[str, dict[str, list[ConceptNode]]] = {

    "physical_design": {
        "floorplanning": [
            ConceptNode("pd_fp_purpose",       "floorplanning", "Purpose and objectives of floorplanning",                          0, ["floorplan","area","utilization","hierarchy"]),
            ConceptNode("pd_fp_utilization",   "floorplanning", "Utilization targets and their trade-offs with routability",        1, ["utilization","congestion","routing","density"]),
            ConceptNode("pd_fp_macro_placement","floorplanning", "Macro placement strategy for timing and congestion",               2, ["macro","placement","timing","congestion","critical path"]),
            ConceptNode("pd_fp_power_domains", "floorplanning", "Power domain planning and voltage island placement",               3, ["power domain","voltage","island","UPF","CPF"]),
            ConceptNode("pd_fp_hierarchical",  "floorplanning", "Hierarchical floorplanning and partition strategy",                4, ["hierarchical","partition","budgeting","interface"]),
        ],
        "power_planning": [
            ConceptNode("pd_pp_purpose",       "power_planning", "Purpose of power planning and PDN fundamentals",                  0, ["power","ground","VDD","VSS","PDN"]),
            ConceptNode("pd_pp_ring_mesh",      "power_planning", "Power ring and mesh design for uniform distribution",            1, ["ring","mesh","straps","width","spacing"]),
            ConceptNode("pd_pp_ir_drop",        "power_planning", "IR drop causes, impact on timing, and mitigation",               2, ["IR drop","voltage","resistance","delay","timing"]),
            ConceptNode("pd_pp_em",             "power_planning", "Electromigration rules and current density limits",              3, ["electromigration","EM","current density","MTTF","reliability"]),
            ConceptNode("pd_pp_dynamic",        "power_planning", "Dynamic IR analysis and power switching impact",                 4, ["dynamic","switching","simultaneous","peak current"]),
        ],
        "placement": [
            ConceptNode("pd_pl_purpose",       "placement",      "Placement objectives and basic algorithms",                      0, ["placement","location","netlist","legalization"]),
            ConceptNode("pd_pl_timing_driven", "placement",      "Timing-driven placement and critical path awareness",            2, ["timing","critical path","slack","placement","TNS"]),
            ConceptNode("pd_pl_congestion",    "placement",      "Congestion analysis and relief techniques",                     2, ["congestion","routing","overflow","GRC","spreading"]),
            ConceptNode("pd_pl_scan_chain",    "placement",      "Scan chain optimization during placement",                      3, ["scan chain","DFT","reorder","wirelength"]),
        ],
        "clock_tree_synthesis": [
            ConceptNode("pd_cts_purpose",      "clock_tree_synthesis", "CTS purpose — what problem it solves",                    0, ["CTS","clock","skew","balance","flip-flop"]),
            ConceptNode("pd_cts_skew",         "clock_tree_synthesis", "Clock skew definition, measurement, and targets",         1, ["skew","insertion delay","latency","target","ps"]),
            ConceptNode("pd_cts_buffer_chain", "clock_tree_synthesis", "Buffer/inverter chain structure and sizing",              2, ["buffer","inverter","drive strength","fanout","chain"]),
            ConceptNode("pd_cts_debug",        "clock_tree_synthesis", "CTS debug workflow — diagnosing skew after CTS",          2, ["debug","log","branch","OCV","CPPR","ECO"], prerequisite="pd_cts_skew"),
            ConceptNode("pd_cts_tool_icc2",    "clock_tree_synthesis", "ICC2-specific CTS commands and constraints",              3, ["ICC2","create_clock","set_clock_uncertainty","CCD"]),
            ConceptNode("pd_cts_useful_skew",  "clock_tree_synthesis", "Useful skew — intentional asymmetry for timing closure",  4, ["useful skew","intentional","setup","hold","borrow"]),
        ],
        "routing": [
            ConceptNode("pd_rt_global",        "routing",        "Global routing concepts and objectives",                        0, ["global routing","GRC","congestion","channel"]),
            ConceptNode("pd_rt_detailed",      "routing",        "Detailed routing — DRC rules and resolution",                  2, ["detailed routing","DRC","spacing","width","via"]),
            ConceptNode("pd_rt_crosstalk",     "routing",        "Crosstalk — noise and timing delta mechanisms",                3, ["crosstalk","aggressor","victim","noise","glitch","delta"]),
            ConceptNode("pd_rt_si",            "routing",        "Signal integrity — shielding, spacing, and ECO",               4, ["signal integrity","shielding","guard","spacing","SI ECO"]),
        ],
        "timing_closure": [
            ConceptNode("pd_tc_sta_basics",    "timing_closure", "STA fundamentals — setup, hold, slack",                        1, ["setup","hold","slack","WNS","TNS","critical path"]),
            ConceptNode("pd_tc_violations",    "timing_closure", "Setup violation identification and ECO options",                2, ["violation","ECO","buffer","upsize","placement"]),
            ConceptNode("pd_tc_hold",          "timing_closure", "Hold violation root causes and fixes",                         2, ["hold","buffer insertion","fill","delay cell"]),
            ConceptNode("pd_tc_ocv",           "timing_closure", "On-chip variation — derating and CPPR",                        3, ["OCV","derating","CPPR","AOCV","POCV","corner"]),
            ConceptNode("pd_tc_mcmm",          "timing_closure", "Multi-corner multi-mode timing analysis",                     4, ["MCMM","corner","mode","PVT","signoff"]),
        ],
    },

    "analog_layout": {
        "basic_layout_concepts": [
            ConceptNode("al_bl_layers",        "basic_layout_concepts", "Layer stack — diffusion, poly, metal layers",            0, ["layer","diffusion","poly","metal","contact","via"]),
            ConceptNode("al_bl_design_rules",  "basic_layout_concepts", "Design rules — spacing, width, enclosure",               1, ["DRC","spacing","width","enclosure","rule"]),
            ConceptNode("al_bl_lvs",           "basic_layout_concepts", "LVS — what it checks and why it fails",                  2, ["LVS","netlist","schematic","shorts","opens"]),
        ],
        "device_matching": [
            ConceptNode("al_dm_techniques",    "device_matching", "Device matching techniques — interdigitation, common centroid", 1, ["matching","interdigitation","common centroid","symmetry"]),
            ConceptNode("al_dm_gradients",     "device_matching", "Process gradients and their effect on matching",               2, ["gradient","oxide","threshold","mismatch","orientation"]),
            ConceptNode("al_dm_mismatch",      "device_matching", "Mismatch quantification — Pelgrom model",                     3, ["Pelgrom","mismatch","area","AVT","sigma"]),
        ],
        "parasitic_awareness": [
            ConceptNode("al_pa_capacitance",   "parasitic_awareness", "Parasitic capacitance sources and minimization",           1, ["parasitic","capacitance","coupling","fringe","area"]),
            ConceptNode("al_pa_resistance",    "parasitic_awareness", "Parasitic resistance — sheet resistance and via resistance", 2, ["sheet resistance","via","metal","resistance","IR"]),
            ConceptNode("al_pa_extraction",    "parasitic_awareness", "Parasitic extraction and post-layout simulation",          3, ["extraction","RCX","Calibre","PEX","simulation"]),
        ],
        "latch_up_and_esd": [
            ConceptNode("al_lu_mechanism",     "latch_up_and_esd", "Latch-up mechanism in CMOS — parasitic BJT",                 1, ["latch-up","PNPN","thyristor","parasitic","BJT"]),
            ConceptNode("al_lu_prevention",    "latch_up_and_esd", "Latch-up prevention — guard rings and substrate contacts",   2, ["guard ring","substrate contact","well","tap","spacing"]),
            ConceptNode("al_esd_protection",   "latch_up_and_esd", "ESD protection structures and placement rules",              3, ["ESD","diode","clamp","CDM","HBM","protection"]),
        ],
    },

    "design_verification": {
        "verification_methodologies": [
            ConceptNode("dv_vm_overview",      "verification_methodologies", "Verification planning and coverage closure",        0, ["verification plan","closure","sign-off","coverage"]),
            ConceptNode("dv_vm_uvm",           "verification_methodologies", "UVM architecture — agent, scoreboard, coverage",   2, ["UVM","agent","driver","monitor","scoreboard","env"]),
            ConceptNode("dv_vm_formal",        "verification_methodologies", "Formal verification — bounded vs unbounded",        3, ["formal","model checking","bounded","property","JasperGold"]),
        ],
        "functional_coverage": [
            ConceptNode("dv_fc_purpose",       "functional_coverage", "Functional coverage purpose vs code coverage",            0, ["functional coverage","code coverage","covergroup","bin"]),
            ConceptNode("dv_fc_covergroup",    "functional_coverage", "Covergroup and coverpoint definition",                    2, ["covergroup","coverpoint","cross","bin","SV"]),
            ConceptNode("dv_fc_closure",       "functional_coverage", "Coverage closure — identifying and closing holes",        3, ["closure","hole","directed test","regression","100%"]),
        ],
        "assertions_and_sva": [
            ConceptNode("dv_sv_immediate",     "assertions_and_sva", "Immediate assertions — syntax and use cases",              1, ["immediate","assert","$fatal","$error","$warning"]),
            ConceptNode("dv_sv_concurrent",    "assertions_and_sva", "Concurrent assertions — clock, property, sequence",       2, ["concurrent","property","sequence","clock","disable iff"]),
            ConceptNode("dv_sv_never_fires",   "assertions_and_sva", "Vacuous passing — assertion that never fires",            3, ["vacuous","never fires","cover","witness","proof"]),
        ],
        "debugging_skills": [
            ConceptNode("dv_db_waveform",      "debugging_skills",   "Waveform debugging — identifying root cause from sim",    1, ["waveform","dump","VCD","FST","toggle","debug"]),
            ConceptNode("dv_db_protocol",      "debugging_skills",   "Protocol-level debug — AXI/APB/AHB violations",           2, ["protocol","AXI","APB","violation","transaction","bus"]),
            ConceptNode("dv_db_formal_cex",    "debugging_skills",   "Counterexample analysis in formal verification",          4, ["counterexample","CEX","trace","waveform","formal"]),
        ],
    },
}


# ══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION — all tunable parameters in one place
# ══════════════════════════════════════════════════════════════════════════════

# Total technical turn budget per candidate level
TURN_BUDGET_PER_LEVEL: dict[str, int] = {
    CandidateLevel.FRESH_GRADUATE:    14,
    CandidateLevel.TRAINED_FRESHER:   16,
    CandidateLevel.EXPERIENCED_JUNIOR: 18,
    CandidateLevel.EXPERIENCED_SENIOR: 20,
}

# Minimum turns per topic to mark as confirmed (not just introduced)
TURNS_TO_CONFIRM: dict[str, int] = {
    CandidateLevel.FRESH_GRADUATE:    2,
    CandidateLevel.TRAINED_FRESHER:   2,
    CandidateLevel.EXPERIENCED_JUNIOR: 3,
    CandidateLevel.EXPERIENCED_SENIOR: 3,
}

# Required depth index per candidate level to consider a topic "fully covered"
DEPTH_REQUIREMENT: dict[str, int] = {
    CandidateLevel.FRESH_GRADUATE:    1,   # basic
    CandidateLevel.TRAINED_FRESHER:   2,   # intermediate
    CandidateLevel.EXPERIENCED_JUNIOR: 3,  # advanced
    CandidateLevel.EXPERIENCED_SENIOR: 4,  # expert
}

# Max difficulty unlocked per phase per level
# Format: phase → level → max_difficulty_index
MAX_DIFFICULTY_BY_PHASE: dict[Phase, dict[str, int]] = {
    Phase.EARLY: {
        CandidateLevel.FRESH_GRADUATE:    1,  # basic
        CandidateLevel.TRAINED_FRESHER:   1,  # basic
        CandidateLevel.EXPERIENCED_JUNIOR: 2, # intermediate
        CandidateLevel.EXPERIENCED_SENIOR: 3, # advanced
    },
    Phase.MID: {
        CandidateLevel.FRESH_GRADUATE:    2,  # intermediate
        CandidateLevel.TRAINED_FRESHER:   3,  # advanced
        CandidateLevel.EXPERIENCED_JUNIOR: 3, # advanced
        CandidateLevel.EXPERIENCED_SENIOR: 4, # expert
    },
    Phase.LATE: {
        CandidateLevel.FRESH_GRADUATE:    2,
        CandidateLevel.TRAINED_FRESHER:   3,
        CandidateLevel.EXPERIENCED_JUNIOR: 4,
        CandidateLevel.EXPERIENCED_SENIOR: 4,
    },
    Phase.CLOSING: {  # same as LATE — no escalation in closing
        CandidateLevel.FRESH_GRADUATE:    2,
        CandidateLevel.TRAINED_FRESHER:   3,
        CandidateLevel.EXPERIENCED_JUNIOR: 4,
        CandidateLevel.EXPERIENCED_SENIOR: 4,
    },
}

# Phase-gated scoring weights [W_urgency, W_depth_gap, W_recency, W_weakness]
# Tuning these changes interview style without touching logic
PHASE_WEIGHTS: dict[Phase, tuple[float, float, float, float]] = {
    Phase.EARLY:   (0.60, 0.20, 0.15, 0.05),  # breadth-first
    Phase.MID:     (0.35, 0.30, 0.20, 0.15),  # balanced
    Phase.LATE:    (0.20, 0.25, 0.20, 0.35),  # exploitation + weakness confirmation
    Phase.CLOSING: (0.10, 0.10, 0.10, 0.70),  # only confirm suspected weak areas
}

# Max consecutive turns on the same topic before forced rotation
MAX_CONSECUTIVE_SAME_TOPIC: dict[Phase, int] = {
    Phase.EARLY:   2,
    Phase.MID:     3,
    Phase.LATE:    4,  # allowed to camp for weakness confirmation
    Phase.CLOSING: 2,
}

# Personal anchor injection turns (absolute tech turn numbers)
PERSONAL_ANCHOR_TURNS: set[int] = {4, 9, 15}
MAX_PERSONAL_ANCHORS: int = 3

# Contradiction: minimum turns between angle_1 and angle_2
CONTRADICTION_MIN_GAP: int = 6


# ══════════════════════════════════════════════════════════════════════════════
# DATA STRUCTURES
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class TopicCoverage:
    """Runtime state for one topic within a session."""
    topic: str
    turns_spent:        int              = 0
    max_depth_reached:  int              = 0   # 0–4
    confidence:         Confidence       = Confidence.UNTESTED
    weak_flag:          WeakFlag         = WeakFlag.NONE
    last_tested_turn:   int              = 0
    consecutive_turns:  int              = 0   # current streak on this topic
    concept_nodes_tested: set[str]       = field(default_factory=set)
    weak_signal_count:  int              = 0   # increments on weak eval; resets on strong
    strong_signal_count: int             = 0


@dataclass
class QuestionIntent:
    """
    Output of the strategy engine. Input to the question generator.
    The LLM receives this and writes natural language for it — nothing more.

    This is the contract between strategy engine and question generator.
    Every field is required. The question generator must not ignore any field.
    """
    # What to ask
    topic:              str
    concept_node_id:    str
    concept_description: str           # passed directly to LLM as constraint
    question_type:      QuestionType
    difficulty:         Difficulty

    # Why this was chosen (for observability and debugging)
    reason:             str            # human-readable explanation of decision
    phase:              Phase
    priority_score:     float          # 0.0–1.0, for logging

    # Context constraints passed to LLM
    candidate_level:    str
    domain:             str
    all_asked_questions: list[str]     # FULL history — not truncated
    asked_concept_nodes: set[str]      # concept nodes already tested this session

    # Optional modifiers
    hint_required:      bool           = False
    hint_text:          Optional[str]  = None
    contradiction_extra: Optional[dict] = None  # for contradiction angle_2
    is_fallback:        bool           = False   # True when curated bank used


@dataclass
class StrategyDecision:
    """
    Full decision output including metadata.
    The QuestionIntent goes to the LLM.
    The metadata goes to observability.
    """
    intent:             QuestionIntent
    current_phase:      Phase
    turns_remaining:    int
    topics_untested:    list[str]
    topics_confirmed:   list[str]
    suspected_weak:     list[str]
    decision_log:       list[str]     # step-by-step reasoning for debugging


# ══════════════════════════════════════════════════════════════════════════════
# STRATEGY ENGINE
# ══════════════════════════════════════════════════════════════════════════════

class StrategyEngine:
    """
    Production strategy engine for the VLSI interview platform.

    Usage:
        engine = StrategyEngine(session)
        decision = engine.decide()
        # pass decision.intent to QuestionGenerator

    After answer is evaluated:
        engine.update_after_evaluation(eval_result)

    Public interface (what other components use):
        decide()                    → StrategyDecision
        update_after_evaluation()   → None
        get_coverage_summary()      → dict  (for report + admin panel)
        get_asked_concept_nodes()   → set[str]  (for RepetitionGuard Layer 3)
        get_phase()                 → Phase
        initialize_coverage_map()   → None  (called once at session start)
    """

    def __init__(self, session: dict):
        self.session = session
        self.resume  = session.get("resume", {})
        self.domain  = self.resume.get("domain", "physical_design")
        self.level   = self.resume.get("level", CandidateLevel.TRAINED_FRESHER)

        # Normalize level string to enum value
        if self.level not in [e.value for e in CandidateLevel]:
            self.level = CandidateLevel.TRAINED_FRESHER

        self.turn_budget   = TURN_BUDGET_PER_LEVEL.get(self.level, 16)
        self.tech_turn     = self._get_tech_turn()
        self.turns_remaining = max(0, self.turn_budget - self.tech_turn)

        # Initialize coverage map if not already in session
        if "strategy_coverage" not in session:
            self.initialize_coverage_map()

        self.coverage: dict[str, TopicCoverage] = session["strategy_coverage"]
        self.domain_concepts = CONCEPT_TAXONOMY.get(self.domain, {})

    # ── Public interface ───────────────────────────────────────────────────

    def initialize_coverage_map(self) -> None:
        """
        Called once at session creation or on first decide() call.
        Builds the coverage map from the domain concept taxonomy.
        Always updates both session and self.coverage to stay in sync.
        """
        coverage: dict[str, TopicCoverage] = {}
        for topic in CONCEPT_TAXONOMY.get(self.domain, {}).keys():
            coverage[topic] = TopicCoverage(topic=topic)
        self.session["strategy_coverage"] = coverage
        self.coverage = coverage  # keep self.coverage in sync

    def decide(self) -> StrategyDecision:
        """
        Main entry point. Returns a full StrategyDecision every turn.
        Deterministic — same session state always produces same decision.
        """
        # Refresh tech_turn and turns_remaining each call
        self.tech_turn = self._get_tech_turn()
        self.turns_remaining = max(0, self.turn_budget - self.tech_turn)
        phase = self.get_phase()
        decision_log: list[str] = []

        # ── Step 1: Check for mandatory overrides first ──────────────────
        # These take priority over scoring. They exist to fulfill commitments
        # made in previous turns (contradiction angle_2, weakness confirmation).

        override = self._check_mandatory_overrides(phase, decision_log)
        if override:
            return self._wrap_decision(override, phase, decision_log)

        # ── Step 2: Check for personal anchor injection ──────────────────
        anchor_intent = self._check_personal_anchor(phase, decision_log)
        if anchor_intent:
            return self._wrap_decision(anchor_intent, phase, decision_log)

        # ── Step 3: Score all topics and select highest priority ─────────
        topic_scores = self._score_all_topics(phase, decision_log)
        selected_topic = max(topic_scores, key=lambda t: topic_scores[t])
        score = topic_scores[selected_topic]
        decision_log.append(
            f"Selected topic '{selected_topic}' with priority score {score:.3f}"
        )

        # ── Step 4: Select question type for chosen topic ────────────────
        q_type = self._select_question_type(selected_topic, phase, decision_log)

        # ── Step 5: Select concept node within topic ─────────────────────
        concept_node = self._select_concept_node(
            selected_topic, q_type, phase, decision_log
        )

        # ── Step 6: Determine difficulty ─────────────────────────────────
        difficulty = self._determine_difficulty(phase, decision_log)

        # ── Step 7: Build QuestionIntent ─────────────────────────────────
        intent = QuestionIntent(
            topic               = selected_topic,
            concept_node_id     = concept_node.node_id,
            concept_description = concept_node.description,
            question_type       = q_type,
            difficulty          = difficulty,
            reason              = "; ".join(decision_log[-3:]),
            phase               = phase,
            priority_score      = score,
            candidate_level     = self.level,
            domain              = self.domain,
            all_asked_questions = self._get_all_asked_questions(),
            asked_concept_nodes = self.get_asked_concept_nodes(),
        )

        return self._wrap_decision(intent, phase, decision_log)

    def update_after_evaluation(self, eval_result: dict, topic: str,
                                 concept_node_id: str) -> None:
        """
        Called by EvaluationEngine after each answer is evaluated.
        Updates coverage map with evaluation results.

        Args:
            eval_result:     dict from LLM evaluation (quality, score, level_gap, etc.)
            topic:           topic that was just evaluated
            concept_node_id: concept node that was just evaluated
        """
        if topic not in self.coverage:
            self.coverage[topic] = TopicCoverage(topic=topic)

        cov = self.coverage[topic]
        quality    = eval_result.get("quality", "adequate")
        score      = int(eval_result.get("score") or 5)
        depth_idx  = self._difficulty_to_index(
            eval_result.get("difficulty", Difficulty.BASIC)
        )

        # Update coverage metrics
        cov.turns_spent        += 1
        cov.max_depth_reached   = max(cov.max_depth_reached, depth_idx)
        cov.last_tested_turn    = self.tech_turn
        cov.concept_nodes_tested.add(concept_node_id)

        # Update consecutive turns on this topic
        last_topic = self.session.get("last_topic")
        if last_topic == topic:
            cov.consecutive_turns += 1
        else:
            cov.consecutive_turns = 1
        self.session["last_topic"] = topic

        # Update weak/strong signals
        if quality in ("weak", "honest_admission") or score <= 4:
            cov.weak_signal_count  += 1
            cov.strong_signal_count = 0
        elif quality == "strong" or score >= 8:
            cov.strong_signal_count += 1
            cov.weak_signal_count   = 0

        # Update confidence level
        required_depth = DEPTH_REQUIREMENT.get(self.level, 2)
        turns_needed   = TURNS_TO_CONFIRM.get(self.level, 2)

        if cov.turns_spent == 1:
            cov.confidence = Confidence.INTRODUCED
        elif (cov.turns_spent >= turns_needed
              and cov.max_depth_reached >= required_depth):
            cov.confidence = Confidence.CONFIRMED
        elif cov.turns_spent >= turns_needed + 3:
            cov.confidence = Confidence.EXHAUSTED

        # Update weak flag
        self._update_weak_flag(cov)

    def get_coverage_summary(self) -> dict:
        """
        Returns structured coverage data for:
        - Report generation (topic_performance map)
        - Admin panel session detail
        - Expert review context
        """
        summary = {}
        for topic, cov in self.coverage.items():
            summary[topic] = {
                "turns_spent":          cov.turns_spent,
                "max_depth_reached":    cov.max_depth_reached,
                "confidence":           cov.confidence,
                "weak_flag":            cov.weak_flag,
                "concept_nodes_tested": list(cov.concept_nodes_tested),
                "consecutive_turns":    cov.consecutive_turns,
            }
        return summary

    def get_asked_concept_nodes(self) -> set[str]:
        """
        Returns all concept node IDs tested this session.
        Used by RepetitionGuard Layer 3 check.
        """
        nodes: set[str] = set()
        for cov in self.coverage.values():
            nodes.update(cov.concept_nodes_tested)
        return nodes

    def get_phase(self) -> Phase:
        """
        Derives current interview phase from tech_turn and turn_budget.
        Deterministic — same inputs always return same phase.
        """
        if self.session.get("phase") in ("greeting", "warmup"):
            return Phase.WARMUP

        t = self.tech_turn
        b = self.turn_budget

        if t <= 6:
            return Phase.EARLY
        elif t <= int(b * 0.70):
            return Phase.MID
        elif t <= int(b * 0.90):
            return Phase.LATE
        else:
            return Phase.CLOSING

    # ── Scoring ───────────────────────────────────────────────────────────

    def _score_all_topics(self, phase: Phase,
                          decision_log: list[str]) -> dict[str, float]:
        """
        Computes priority score for every topic in the domain.
        Returns normalized scores 0.0–1.0 for all topics.
        All scores are deterministic given session state.
        """
        weights = PHASE_WEIGHTS[phase]
        W1, W2, W3, W4 = weights

        untested_count = sum(
            1 for cov in self.coverage.values()
            if cov.confidence == Confidence.UNTESTED
        )

        scores: dict[str, float] = {}

        for topic, cov in self.coverage.items():
            # Skip exhausted topics — they are fully covered
            if cov.confidence == Confidence.EXHAUSTED:
                scores[topic] = 0.0
                continue

            # Skip if consecutive_turns exceeds phase limit
            max_consec = MAX_CONSECUTIVE_SAME_TOPIC[phase]
            if (cov.consecutive_turns >= max_consec
                    and self.session.get("last_topic") == topic):
                scores[topic] = 0.0
                decision_log.append(
                    f"Topic '{topic}' blocked — hit consecutive limit {max_consec}"
                )
                continue

            # Component 1 — Urgency (normalized to 0–1)
            raw_urgency = untested_count / max(self.turns_remaining, 1)
            urgency_score = min(1.0, raw_urgency)
            # Untested topics get full urgency; introduced/confirmed get partial
            if cov.confidence == Confidence.UNTESTED:
                urgency_component = urgency_score
            elif cov.confidence == Confidence.INTRODUCED:
                urgency_component = urgency_score * 0.5
            else:
                urgency_component = urgency_score * 0.2

            # Component 2 — Depth gap (already 0–1)
            required_depth = DEPTH_REQUIREMENT.get(self.level, 2)
            depth_gap = max(0, required_depth - cov.max_depth_reached)
            depth_gap_score = depth_gap / max(required_depth, 1)

            # Component 3 — Recency (normalized to 0–1)
            turns_since = self.tech_turn - cov.last_tested_turn
            recency_score = min(1.0, turns_since / max(self.turn_budget, 1))

            # Component 4 — Weakness confirmation
            if cov.weak_flag == WeakFlag.SUSPECTED:
                weakness_score = 0.8
            elif cov.weak_flag == WeakFlag.CONFIRMED_STRONG:
                weakness_score = -0.3   # deprioritize — proven strong
            elif cov.weak_flag == WeakFlag.CONFIRMED_WEAK:
                weakness_score = 0.1    # still low — already confirmed, no need to repeat
            else:
                weakness_score = 0.0

            # Composite score
            raw_score = (
                W1 * urgency_component
                + W2 * depth_gap_score
                + W3 * recency_score
                + W4 * weakness_score
            )

            # Clamp to 0–1
            scores[topic] = max(0.0, min(1.0, raw_score))

        decision_log.append(
            f"Phase {phase.value} — top topics: "
            + ", ".join(
                f"{t}={s:.2f}"
                for t, s in sorted(scores.items(), key=lambda x: -x[1])[:3]
            )
        )
        return scores

    # ── Question type selection ───────────────────────────────────────────

    def _select_question_type(self, topic: str, phase: Phase,
                               decision_log: list[str]) -> QuestionType:
        """
        Selects question type based on topic coverage state and phase.
        Preserves the existing 8-rule sequencer logic but integrates
        topic-level awareness from the coverage map.
        """
        cov             = self.coverage.get(topic, TopicCoverage(topic=topic))
        last_type       = self.session.get("last_question_type", "")
        last_eval       = self.session.get("last_eval_quality", "adequate")
        last_confidence = self.session.get("last_confidence", "medium")
        last_topic      = self.session.get("last_topic", "")
        recovery_count  = self.session.get("recovery_attempts_per_topic", {}).get(topic, 0)

        # Rule 1: Recovery from honest admission on same topic
        if (last_eval == "honest_admission"
                and last_topic == topic
                and recovery_count < 2):
            decision_log.append("Rule: honest_admission → recovery_probe")
            return QuestionType.RECOVERY_PROBE

        # Rule 2: Recovery limit reached — move on
        if (last_type == QuestionType.RECOVERY_PROBE
                and recovery_count >= 2
                and last_topic == topic):
            decision_log.append("Rule: recovery limit reached → force new topic")
            return QuestionType.DEFINITION

        # Rule 3: Poor articulation → ask for practical example
        if last_eval == "poor_articulation" and last_topic == topic:
            decision_log.append("Rule: poor_articulation → practical_example")
            return QuestionType.PRACTICAL_EXAMPLE

        # Rule 4: New topic — always start with definition
        if cov.confidence == Confidence.UNTESTED:
            decision_log.append("Rule: untested topic → definition")
            return QuestionType.DEFINITION

        # Rule 5: Definition answered → scenario
        if last_type == QuestionType.DEFINITION and last_topic == topic:
            decision_log.append("Rule: definition complete → scenario")
            return QuestionType.SCENARIO

        # Rule 6: Scenario answered with high confidence but weak accuracy → why_probe
        if (last_type == QuestionType.SCENARIO
                and last_topic == topic
                and last_confidence == "high"
                and last_eval in ("weak", "adequate")):
            decision_log.append("Rule: scenario+high_confidence+weak → why_probe")
            return QuestionType.WHY_PROBE

        # Rule 7: Mid/late phase — numerical probe if topic has depth
        if (phase in (Phase.MID, Phase.LATE)
                and cov.max_depth_reached >= 1
                and last_type in (QuestionType.SCENARIO,
                                   QuestionType.WHY_PROBE,
                                   QuestionType.PRACTICAL_EXAMPLE)
                and last_topic == topic):
            decision_log.append("Rule: post-scenario in mid/late → numerical")
            return QuestionType.NUMERICAL

        # Rule 8: Default for introduced topic — go deeper with scenario
        if cov.confidence == Confidence.INTRODUCED:
            decision_log.append("Rule: introduced topic → scenario for depth")
            return QuestionType.SCENARIO

        # Default
        decision_log.append("Rule: default → definition")
        return QuestionType.DEFINITION

    # ── Concept node selection ────────────────────────────────────────────

    def _select_concept_node(self, topic: str, q_type: QuestionType,
                              phase: Phase,
                              decision_log: list[str]) -> ConceptNode:
        """
        Selects the most appropriate untested concept node within a topic.
        Respects prerequisites — never asks advanced nodes before foundational.
        Falls back to first available node if all tested.
        """
        nodes = self.domain_concepts.get(topic, [])
        cov   = self.coverage.get(topic, TopicCoverage(topic=topic))
        max_depth_idx = MAX_DIFFICULTY_BY_PHASE[phase].get(self.level, 2)
        asked_nodes   = cov.concept_nodes_tested

        # Filter: not yet tested, within depth budget, prerequisites met
        candidates = [
            n for n in nodes
            if n.node_id not in asked_nodes
            and n.depth <= max_depth_idx
            and (n.prerequisite is None or n.prerequisite in asked_nodes)
        ]

        if candidates:
            # Prefer the deepest available node — push depth while allowed
            selected = max(candidates, key=lambda n: n.depth)
            decision_log.append(
                f"Concept node: '{selected.node_id}' (depth {selected.depth})"
            )
            return selected

        # All concept nodes tested or blocked — find deepest tested node
        # Use it for follow-up (this signals EXHAUSTED soon)
        tested_nodes = [n for n in nodes if n.node_id in asked_nodes]
        if tested_nodes:
            selected = max(tested_nodes, key=lambda n: n.depth)
            decision_log.append(
                f"Concept node: revisiting '{selected.node_id}' — all nodes tested"
            )
            return selected

        # Final fallback — first node in taxonomy
        fallback = nodes[0] if nodes else ConceptNode(
            node_id=f"{topic}_general",
            topic=topic,
            description=f"General {topic.replace('_',' ')} question",
            depth=1,
            keywords=[topic],
        )
        decision_log.append(f"Concept node: taxonomy fallback '{fallback.node_id}'")
        return fallback

    # ── Difficulty determination ──────────────────────────────────────────

    def _determine_difficulty(self, phase: Phase,
                               decision_log: list[str]) -> Difficulty:
        """
        Maps session difficulty_level (int) to Difficulty enum,
        capped by phase + level constraints.
        """
        session_diff_idx  = self.session.get("difficulty_level", 1)
        max_allowed_idx   = MAX_DIFFICULTY_BY_PHASE[phase].get(self.level, 2)
        effective_idx     = min(session_diff_idx, max_allowed_idx)
        difficulty_labels = ["foundational","basic","intermediate","advanced","expert"]
        difficulty_str    = difficulty_labels[effective_idx]
        decision_log.append(
            f"Difficulty: session={session_diff_idx}, "
            f"phase_cap={max_allowed_idx}, effective={difficulty_str}"
        )
        return Difficulty(difficulty_str)

    # ── Mandatory overrides ───────────────────────────────────────────────

    def _check_mandatory_overrides(self, phase: Phase,
                                    decision_log: list[str]
                                    ) -> Optional[QuestionIntent]:
        """
        Checks for commitments that override normal scoring.
        Currently handles:
          - Contradiction angle_2 (promise made when angle_1 was asked)
          - Weakness confirmation (suspected weak topics in late/closing)
        """
        # Override 1: Contradiction angle_2 due
        contradiction = self._get_due_contradiction()
        if contradiction:
            pair  = contradiction["pair"]
            topic = pair["topic"]
            angle2_node = self._get_concept_node_for_topic(topic)
            decision_log.append(
                f"OVERRIDE: contradiction angle_2 due on topic '{topic}'"
            )
            return QuestionIntent(
                topic               = topic,
                concept_node_id     = angle2_node.node_id,
                concept_description = angle2_node.description,
                question_type       = QuestionType.CONTRADICTION,
                difficulty          = self._determine_difficulty(phase, []),
                reason              = f"Contradiction angle_2 due on {topic}",
                phase               = phase,
                priority_score      = 1.0,
                candidate_level     = self.level,
                domain              = self.domain,
                all_asked_questions = self._get_all_asked_questions(),
                asked_concept_nodes = self.get_asked_concept_nodes(),
                contradiction_extra = contradiction,
            )

        # Override 2: Suspected weak topic in late/closing phase
        if phase in (Phase.LATE, Phase.CLOSING):
            suspected = [
                topic for topic, cov in self.coverage.items()
                if cov.weak_flag == WeakFlag.SUSPECTED
            ]
            if suspected:
                # Pick the suspected topic with most turns remaining for confirmation
                topic = suspected[0]
                node  = self._get_concept_node_for_topic(topic)
                decision_log.append(
                    f"OVERRIDE: confirming suspected weak topic '{topic}'"
                )
                return QuestionIntent(
                    topic               = topic,
                    concept_node_id     = node.node_id,
                    concept_description = node.description,
                    question_type       = QuestionType.SCENARIO,
                    difficulty          = self._determine_difficulty(phase, []),
                    reason              = f"Confirming suspected weakness on {topic}",
                    phase               = phase,
                    priority_score      = 1.0,
                    candidate_level     = self.level,
                    domain              = self.domain,
                    all_asked_questions = self._get_all_asked_questions(),
                    asked_concept_nodes = self.get_asked_concept_nodes(),
                )

        return None

    def _check_personal_anchor(self, phase: Phase,
                                decision_log: list[str]
                                ) -> Optional[QuestionIntent]:
        """
        Injects personal anchor questions at defined turn numbers.
        Personal anchors are not tied to a concept node —
        they test authentic experience, not technical content.
        """
        anchor_count = self.session.get("anchor_count", 0)
        if (anchor_count < MAX_PERSONAL_ANCHORS
                and self.tech_turn in PERSONAL_ANCHOR_TURNS
                and phase in (Phase.MID, Phase.LATE)):
            last_topic = self.session.get("last_topic", "")
            topic      = last_topic or list(self.coverage.keys())[0]
            node       = self._get_concept_node_for_topic(topic)
            decision_log.append(
                f"Personal anchor injection at tech_turn={self.tech_turn}"
            )
            return QuestionIntent(
                topic               = topic,
                concept_node_id     = node.node_id,
                concept_description = f"Personal experience with {topic.replace('_',' ')}",
                question_type       = QuestionType.PERSONAL_ANCHOR,
                difficulty          = self._determine_difficulty(phase, []),
                reason              = f"Personal anchor turn {self.tech_turn}",
                phase               = phase,
                priority_score      = 0.9,
                candidate_level     = self.level,
                domain              = self.domain,
                all_asked_questions = self._get_all_asked_questions(),
                asked_concept_nodes = self.get_asked_concept_nodes(),
            )
        return None

    # ── Helpers ───────────────────────────────────────────────────────────

    def _wrap_decision(self, intent: QuestionIntent, phase: Phase,
                        decision_log: list[str]) -> StrategyDecision:
        return StrategyDecision(
            intent           = intent,
            current_phase    = phase,
            turns_remaining  = self.turns_remaining,
            topics_untested  = [t for t,c in self.coverage.items()
                                  if c.confidence == Confidence.UNTESTED],
            topics_confirmed = [t for t,c in self.coverage.items()
                                  if c.confidence == Confidence.CONFIRMED],
            suspected_weak   = [t for t,c in self.coverage.items()
                                  if c.weak_flag == WeakFlag.SUSPECTED],
            decision_log     = decision_log,
        )

    def _get_tech_turn(self) -> int:
        return max(0, self.session.get("turn", 0)
                   - self.session.get("warmup_turns", 2) - 1)

    def _get_all_asked_questions(self) -> list[str]:
        """Returns ALL questions asked this session — no truncation.
        This is the RepetitionGuard Layer 1 input."""
        return [
            h.get("question", "")
            for h in self.session.get("history", [])
            if h.get("question")
        ]

    def _get_concept_node_for_topic(self, topic: str) -> ConceptNode:
        """Returns the deepest tested concept node, or first node if none tested."""
        nodes      = self.domain_concepts.get(topic, [])
        cov        = self.coverage.get(topic, TopicCoverage(topic=topic))
        tested     = [n for n in nodes if n.node_id in cov.concept_nodes_tested]
        untested   = [n for n in nodes if n.node_id not in cov.concept_nodes_tested]
        if untested:
            return untested[0]
        if tested:
            return max(tested, key=lambda n: n.depth)
        return ConceptNode(
            node_id=f"{topic}_fallback", topic=topic,
            description=topic.replace("_"," "), depth=1, keywords=[topic]
        )

    def _get_due_contradiction(self) -> Optional[dict]:
        """
        Checks if any contradiction pair has angle_1 asked and
        enough turns have passed for angle_2.
        Delegates to existing contradiction tracking in session.
        """
        from config import CONTRADICTION_PAIRS
        domain = self.domain
        pairs  = CONTRADICTION_PAIRS.get(domain, [])
        asked  = self.session.get("contradiction_asked", {})

        for pair in pairs:
            topic = pair["topic"]
            state = asked.get(topic, "none")
            if state == "angle_1_asked":
                turns_since = self.tech_turn - asked.get(f"{topic}_turn", 0)
                if turns_since >= CONTRADICTION_MIN_GAP:
                    return {"pair": pair, "angle": "angle_2"}
        return None

    def _difficulty_to_index(self, difficulty) -> int:
        mapping = {
            "foundational": 0, "basic": 1, "intermediate": 2,
            "advanced": 3, "expert": 4,
        }
        if isinstance(difficulty, Difficulty):
            return mapping.get(difficulty.value, 1)
        return mapping.get(str(difficulty), 1)

    def _update_weak_flag(self, cov: TopicCoverage) -> None:
        """Updates weak_flag based on accumulated signal counts."""
        if cov.turns_spent < 1:
            return
        confirm_threshold = TURNS_TO_CONFIRM.get(self.level, 2)
        if cov.strong_signal_count >= confirm_threshold:
            cov.weak_flag = WeakFlag.CONFIRMED_STRONG
        elif cov.weak_signal_count == 1 and cov.turns_spent >= 1:
            cov.weak_flag = WeakFlag.SUSPECTED
        elif cov.weak_signal_count >= confirm_threshold:
            cov.weak_flag = WeakFlag.CONFIRMED_WEAK
        elif cov.turns_spent > 0 and cov.weak_signal_count == 0:
            cov.weak_flag = WeakFlag.NONE


# ══════════════════════════════════════════════════════════════════════════════
# SESSION INTEGRATION HELPERS
# These are the functions called from the existing main.py / agent.py
# They wrap StrategyEngine so the rest of the codebase uses a simple interface
# ══════════════════════════════════════════════════════════════════════════════

def get_or_create_engine(session: dict) -> StrategyEngine:
    """
    Returns the StrategyEngine for a session, creating it if needed.
    Call this instead of constructing StrategyEngine directly.
    """
    engine = StrategyEngine(session)
    if "strategy_coverage" not in session:
        engine.initialize_coverage_map()
    return engine


def strategy_decide(session: dict) -> StrategyDecision:
    """
    Single entry point for the rest of the codebase.
    Returns a StrategyDecision every technical turn.

    Replaces: decide_question_type(session)
    """
    engine = get_or_create_engine(session)
    return engine.decide()


def strategy_update(session: dict, eval_result: dict,
                    topic: str, concept_node_id: str) -> None:
    """
    Single entry point for post-evaluation updates.
    Call this after every evaluation completes.

    Replaces: the scattered session state updates in submit_answer()
    """
    engine = get_or_create_engine(session)
    engine.update_after_evaluation(eval_result, topic, concept_node_id)


def strategy_coverage_for_report(session: dict) -> dict:
    """
    Returns structured topic coverage for report generation.
    Replaces: topic_map computation in generate_report()
    """
    engine = get_or_create_engine(session)
    return engine.get_coverage_summary()